### ISSUE TITLE
Export Xml file not created

### ISSUE THREAD

**Issue by andrewphilipsmith** [mapaction/mapactionpy_controller#127]
# How to reproduce
Create one or more maps using the `maps --build` option. eg:
`env\Scripts\mapchef.exe maps --build %event_desc_path% --map-number MA9004`

# Expected Result
The following files should be produced:
* PDF
* jpeg
* thumbnail
* XML
* Zip

# Actual result
Only these files are produced:
* PDF
* jpeg
* thumbnail

The XML and Zip files are missing.
The following error message is returned:
```
2021-04-26 18:12:41,612 - mapactionpy_controller.main_stack - WARNING (main_stack +ln99) ;- Failed to export the maps and create zipfile
error message=exportXmlFileLocation

Traceback (most recent call last):
  File "c:\gocd\agent\pipelines\guatemala\env\lib\site-packages\mapactionpy_controller\steps.py", line 59, in run
    result = self.func(**kwargs)
  File "c:\gocd\agent\pipelines\guatemala\env\lib\site-packages\mapactionpy_controller\plugin_base.py", line 257, in export_maps
    self.zip_exported_files(export_params)
  File "c:\gocd\agent\pipelines\guatemala\env\lib\site-packages\mapactionpy_controller\plugin_base.py", line 287, in zip_exported_files
    mdr_xml_file_path = export_params['exportXmlFileLocation']
KeyError: 'exportXmlFileLocation'

2021-04-26 18:12:41,612 main_stack mapactionpy_controller.main_stack.parse_feedback +99: WARNING  Failed to export the maps and create zipfile
error message=exportXmlFileLocation

Traceback (most recent call last):
  File "c:\gocd\agent\pipelines\guatemala\env\lib\site-packages\mapactionpy_controller\steps.py", line 59, in run
    result = self.func(**kwargs)
  File "c:\gocd\agent\pipelines\guatemala\env\lib\site-packages\mapactionpy_controller\plugin_base.py", line 257, in export_maps
    self.zip_exported_files(export_params)
  File "c:\gocd\agent\pipelines\guatemala\env\lib\site-packages\mapactionpy_controller\plugin_base.py", line 287, in zip_exported_files
    mdr_xml_file_path = export_params['exportXmlFileLocation']
KeyError: 'exportXmlFileLocation'
```

**Comment by andrewphilipsmith** [comment]
Fixed by https://github.com/mapaction/mapactionpy_controller/pull/128
