### ISSUE TITLE
Incomprehesible error message is layerproperties.json references a non-existant map frame

### ISSUE THREAD

**Issue by andrewphilipsmith** [mapaction/mapactionpy_controller#24]
How to reproduce
===========
* Create a map template and layerProperties.json
* Edit the layerProperties.json so that it references a Map Frame which does not exist in the map template.
* Attempt to run arcmap_runner using the map template and layerProperties.json

Expected behaviour
============
arcmap_runner should return a meaningful descriptive error message.

Actual behaviour
==========
This is the error message returned:
```
Traceback (most recent call last):
  File "C:\py27arcgis106\ArcGIS10.6\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\py27arcgis106\ArcGIS10.6\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\code\github\mapactionpy_arcmap\mapactionpy_arcmap\arcmap_runner.py", line 82, in <module>
    main(args)
  File "D:\code\github\mapactionpy_arcmap\mapactionpy_arcmap\arcmap_runner.py", line 51, in main
    chef.cook(productName, countryName)
  File "mapactionpy_arcmap\map_chef.py", line 65, in cook
  File "mapactionpy_arcmap\map_chef.py", line 150, in processLayer
IndexError: list index out of range
```

**Comment by andrewphilipsmith** [comment]
This should have been openned against `mapactionpy_arcmap`. I have now openned https://github.com/mapaction/mapactionpy_arcmap/issues/8 instead. Closing this message here.
